language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: my-awesome-coursemanager
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
